version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      # --- IMPORTANT: Replace these with your actual keys/URLs ---
      # For local development, create a .env file in the project root.
      # For GitHub Actions, set these as repository secrets.
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL} # Placeholder for future Supabase integration
      SUPABASE_KEY: ${SUPABASE_KEY} # Placeholder for future Supabase integration
      # ---------------------------------------------------------
      FLASK_APP: app.py
      FLASK_ENV: development
    restart: unless-stopped
