version: '3.8'

services:
  tobi-trivia-app: # Single service name for the combined app
    build:
      context: . # Build context is the root of the project
      dockerfile: ./Dockerfile # Points to the new combined Dockerfile
    ports:
      - "80:5000" # Map host port 80 to container port 5000 (where Flask runs)
    environment:
      # These variables will be read from your .env file or GitHub Secrets
      # They are passed directly to the Flask application
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    restart: unless-stopped
