    name: Build and Push Docker Image

    on:
      push:
        branches:
          - main
      release:
        types: [published]

    jobs:
      build-and-push:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write # Needed to push images to GHCR

        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2 # For multi-architecture builds

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2 # For multi-architecture builds

          - name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Extract Docker metadata (frontend)
            id: meta-frontend
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/frontend
              tags: |
                type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                type=ref,event=branch
                type=semver,pattern={{version}}
                type=sha,format=long

          - name: Build and push Docker image (Frontend)
            uses: docker/build-push-action@v4
            with:
              context: . # Build context is the root of the project
              file: ./frontend/Dockerfile.frontend # Specify the Dockerfile for frontend
              platforms: linux/amd64,linux/arm64 # Build for multiple architectures
              push: true
              tags: ${{ steps.meta-frontend.outputs.tags }}
              labels: ${{ steps.meta-frontend.outputs.labels }}

          - name: Extract Docker metadata (backend)
            id: meta-backend
            uses: docker/metadata-action@v4
            with:
              images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/backend
              tags: |
                type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
                type=ref,event=branch
                type=semver,pattern={{version}}
                type=sha,format=long

          - name: Build and push Docker image (Backend)
            uses: docker/build-push-action@v4
            with:
              context: . # Build context is the root of the project
              file: ./backend/Dockerfile.backend # Specify the Dockerfile for backend
              platforms: linux/amd64,linux/arm64 # Build for multiple architectures
              push: true
              tags: ${{ steps.meta-backend.outputs.tags }}
              labels: ${{ steps.meta-backend.outputs.labels }}
    