name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push images to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 # For multi-architecture builds

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # For multi-architecture builds

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (combined app)
        id: meta-app
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} # Image name for the single app
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,format=long

      - name: Build and push Docker image (Combined App)
        uses: docker/build-push-action@v4
        with:
          context: . # Build context is the root of the project
          file: ./Dockerfile # Specify the new combined Dockerfile at the root
          platforms: linux/amd64,linux/arm64 # Build for multiple architectures
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
